version: '3.3'

services:

    node:
        build:
            context: ./node
            args:
                - NODE_VERSION=latest
                - PROJECT_PATH=/opt/app/
                - NODE_ENV=production
                - YARN=false
        volumes:
            - ./:/opt/app
        entrypoint: run-nodock "nodemon -L --watch ./ app.js"
        tty: true
        ports: 
            -   "8000:3000"

    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet